Upgrade of Mobile Portfolio App for Desktop Responsivness
anyars-encarta/Porfolio pull request #7
Opened 2023-06-15 08:45 UTC by anyars-encarta

In this project, I enhanced my Mobile Portfolio app to be responsive to desktop screens.
I used:

- [ ] HTML
- [ ] CSS
- [ ] Linters
- [ ] I also used Grid and Flexbox to display contents on the page

2023-06-15 09:44 UTC, AlphaNtihinduka requested changes
## Hi @anyars-encarta 🙋‍♂️
Good job working on desktop version of your portifolio. You have done the design to do the expectation and incredibly well. 👏  

TO HIGHLIGHT:
- Used media queries ✔️ 
- Well-structured files ✅

# STATUS: Required Changes :recycle: 

![close](https://user-images.githubusercontent.com/99394374/210771148-619a4265-33b2-4e68-8901-6bb52693d6de.gif)

## Required changes :recycle: 
- Kindly consider the inline review comments ☺️
- Finally, you should make sure that your portifolio doesn't have the horizontal scroll. The experience of scrolling horizontally can makes the screen judder and create a headache inducing feeling. Therefore I suggest that you ensure that your portifolio is horizontal scroll free.

https://github.com/anyars-encarta/Porfolio/assets/99394374/ae3cc17f-2ff9-485a-957d-c231fea68e5d



## Optional suggestions
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or slack channel if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK :crossed_fingers: :four_leaf_clover:

2023-06-15 09:44 UTC, AlphaNtihinduka commented on index.css
> +  }
- [ ] You may need to ensure that your portifolio matches the Figma design as much as possible. If you are keen at this heading, you can realize that it crosses into the above line. For this reason, I suggest that you consider having the heading below the line and at the same level as the image ☺️.

Your design 😎 
![image](https://github.com/anyars-encarta/Porfolio/assets/99394374/0119abda-6279-4a73-af9d-b2781ac0321b)

Figma design 😎 
![image](https://github.com/anyars-encarta/Porfolio/assets/99394374/318089c1-d6b3-4ed3-8a31-39f6fc04df6c)

2023-06-15 09:44 UTC, AlphaNtihinduka commented on index.html
> +          </article>
- [ ] Please try as much as possible to stick to the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?type=design&node-id=1-1471&t=E5AVHIf7a3eVNCi2-0). There should be a spacing on the left of the cards to ensure that your portifolio is more user-friendly ☺️.
- [ ] In addition, the spacing between the cards should be reduced to match the Figma design ☺️.
Your design 😎 
![image](https://github.com/anyars-encarta/Porfolio/assets/99394374/b75f73a6-3d0f-4141-b222-669e799165cd)

Figma design 😎 
![image](https://github.com/anyars-encarta/Porfolio/assets/99394374/e593cb2d-df3c-4f5b-bd0c-3de5e414e6b1)

2023-06-15 09:44 UTC, AlphaNtihinduka commented on index.html
>            <section class="works-centered">
- [ ] I suggest to consider aligning the section to the left such that it is at the same level as the heading and the cards. This is to ensure that we stick the original Figma design ☺️.
- [ ] In addition, `project-list` should not overlap into the `p`. This makes your design messy and less user-friendly ☺️. Please fix this to make sure that your portifolio is professional 👍 
- [ ] Finally on this section, I kindly suggest to make sure that the `p` text is responsive in all the desktop screen sizes 👍 

Your design 😎 
![image](https://github.com/anyars-encarta/Porfolio/assets/99394374/5b81f824-1b7c-4ee0-b934-c4862bcec367)

Figma design 😎 
![image](https://github.com/anyars-encarta/Porfolio/assets/99394374/45db50e7-0545-463d-b688-82caa3abea3f)

2023-06-15 09:44 UTC, AlphaNtihinduka commented on index.css
> +  }
- [ ] I have noticed that there is a spacing in the left side of the `header`. Kindly make sure that this spacing is removed to ensure that your portifolio has good UI and hence professional ☺️ 

Your design 😎 
![image](https://github.com/anyars-encarta/Porfolio/assets/99394374/3220321b-906a-46c8-a4f7-6354b111f600)

Figma design 😎 
![image](https://github.com/anyars-encarta/Porfolio/assets/99394374/b851a480-37b9-4ef6-a64f-3050c8472b9f)

2023-06-15 14:24 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @anyars-encarta , |
|Great work on making the changes requested by a previous reviewer 👏, You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet. |
| <img src="https://media4.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif"/> |

## Highlights

- [ ]... ✅ Green linters
- [ ]... ✅ Great readme file

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-15 14:24 UTC, joskalenda commented on index.css
> +  main {
- [ ] As mentioned in the previous CR, your application is not responsive on this screen size YET, I think you should have started the desktop design from this, and the value above it should match or be easily modified, see the record below, 

![6](https://github.com/anyars-encarta/Porfolio/assets/77843050/64ceee69-a988-4f16-b51d-31d16c0c0178)

2023-06-16 08:40 UTC, AdnanOlarmmi approved these changes
Hi @anyars-encarta,

This is Adnan Is-haq, your beloved code reviewer, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Approved office man](https://user-images.githubusercontent.com/41163571/219113922-5007d6bb-ff59-4916-b6d3-e5aad3cb4051.gif)

## Highlights
- Fixed suggested changes.

## Optional suggestions
_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-16 08:45 UTC, anyars-encarta commented
Thanks @AdnanOlarmmi . I am very grateful. I would very much love to learn from you. I am following you on GitHub from here.

2023-06-16 08:54 UTC, merged